import { Red_Hat_Display } from 'next/font/google';

import ShowcaseGuard from '../components/showcase/showcase-guard';

import type { Metadata } from 'next';

import './globals.css';

const redHatDisplay = Red_Hat_Display({
  subsets: ['latin'],
  variable: '--font-red-hat-display',
  display: 'swap',
  fallback: ['Arial', 'Helvetica', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${redHatDisplay.variable}  h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        className={`${redHatDisplay.variable} min-h-full flex flex-col`}
        suppressHydrationWarning
      >
        <ShowcaseGuard>{children}</ShowcaseGuard>
      </body>
    </html>
  );
}
