import { Suspense } from 'react';

import { Red_Hat_Display } from 'next/font/google';
import Script from 'next/script';

import AppRouteLoader from '@/components/common/AppRouteLoader';
import { LoadConfig } from '@/components/loadConfig';
import ToastProvider from '@/components/ToastProvider';

import ShowcaseGuard from '../components/showcase/showcase-guard';

import type { Metadata } from 'next';

import './globals.css';

const redHatDisplay = Red_Hat_Display({
  subsets: ['latin'],
  variable: '--font-red-hat-display',
  display: 'swap',
  fallback: ['Arial', 'Helvetica', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Compare Household bills | Billgoose',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${redHatDisplay.variable}  h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        className={`${redHatDisplay.variable} min-h-full flex flex-col`}
        suppressHydrationWarning
      >
        <Suspense fallback={null}>
          <AppRouteLoader />
        </Suspense>
        <ShowcaseGuard>
          <ToastProvider>{children}</ToastProvider>
          {/* {children} */}
        </ShowcaseGuard>
        <LoadConfig />
        {/* <ToastProvider>{children}</ToastProvider> */}

        <Script
          id="tradedoubler-landing"
          strategy="afterInteractive"
        >
          {`
            // 👇 THIS IS WHERE THE CODE GOES
            var td_script = document.createElement('script');
            td_script.type = 'text/javascript';
            td_script.async = true;
            td_script.src = 'https://t.tradedoubler.com/register?programId=${process.env.NEXT_PUBLIC_TRADEDOUBLER_PROGRAM_ID}&domain=${process.env.NEXT_PUBLIC_DOMAIN}';
            document.getElementsByTagName('head')[0].appendChild(td_script);
          `}
        </Script>
      </body>
    </html>
  );
}
